=== davudmurtazin/Task9/src/test-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 	xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.davud-test.org/test-schema"
           xmlns:tns="http://www.davud-test.org/test-schema"
           elementFormDefault="qualified">

    <element name="test">
        <complexType>
            <sequence>
                <element name="dataSelection" type="tns:DataSelection" minOccurs="1" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="DataSelection">
        <sequence>
            <element name="question" type="tns:Question" minOccurs="0" maxOccurs="unbounded" />
            <element name="subject" type="tns:Subject" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="questionType"></enumeration>
                    <enumeration value="subjectType"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Question">
        <sequence>
            <element name="questionID" type="int" />
            <element name="questionSubjectID" type="int" />
            <element name="content" type="string" />
            <element name="rightAnswer" type="string" />
        </sequence>
    </complexType>

    <complexType name="Subject">
        <sequence>
            <element name="subjectID" type="int" />
            <element name="subjectName" type="string" />
        </sequence>
    </complexType>
</schema>

=== davudmurtazin/Task9/src/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<test 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.davud-test.org/test-schema"
             xsi:schemaLocation="http://www.davud-test.org/test-schema test-schema.xsd">
    <dataSelection type = "questionType">
        <question>
            <questionID>1</questionID>
            <questionSubjectID>1</questionSubjectID>
            <content>2x2?</content>
            <rightAnswer>4</rightAnswer>
        </question>
        <question>
            <questionID>2</questionID>
            <questionSubjectID>2</questionSubjectID>
            <content>Capital of Belarus?</content>
            <rightAnswer>Minsk</rightAnswer>
        </question>
        <question>
            <questionID>1</questionID>
            <questionSubjectID>1</questionSubjectID>
            <content>2x2?</content>
            <rightAnswer>4</rightAnswer>
        </question>
    </dataSelection>
    <dataSelection type = "subjectType">
        <subject>
            <subjectID>1</subjectID>
            <subjectName>math</subjectName>
        </subject>
        <subject>
            <subjectID>2</subjectID>
            <subjectName>geography</subjectName>
        </subject>
        <subject>
            <subjectID>3</subjectID>
            <subjectName>history</subjectName>
        </subject>
        <subject>
            <subjectID>4</subjectID>
            <subjectName>computer science</subjectName>
        </subject>
        <subject>
            <subjectID>5</subjectID>
            <subjectName>programing</subjectName>
        </subject>
    </dataSelection>
</test>
